---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Causal Inference in R Workshop

### Slides
* [00 Intro](https://causal-inference-r-workshop.netlify.app/00-intro.html)
* [01 Whole Game](https://causal-inference-r-workshop.netlify.app/01-causal_modeling_whole_game.html)
* [02 When Standard Methods Succeed](https://causal-inference-r-workshop.netlify.app/02-when-standard-methods-succeed.html)
* [03 Causal Inference with `group_by` and `summarise`](https://causal-inference-r-workshop.netlify.app/03-causal-inference-with-group-by-and-summarise.html)
* [04 Causal Diagrams](https://causal-inference-r-workshop.netlify.app/04-dags.html)
* [05 Introduction to Propensity Scores](https://causal-inference-r-workshop.netlify.app/05-pscores.html)
* [06 Using Propensity Scores](https://causal-inference-r-workshop.netlify.app/06-using-pscores.html)
* [07 Checking Propensity Scores](https://causal-inference-r-workshop.netlify.app/07-pscore-diagnostics.html)
* [08 Fitting the outcome model](https://causal-inference-r-workshop.netlify.app/08-outcome-model.html)
* [09 Continuous Exposures](https://causal-inference-r-workshop.netlify.app/09-continuous-exposures.html)
* [10 G-Computation](https://causal-inference-r-workshop.netlify.app/10-g-computation.html)
* [11 Tipping Point Sensitivity Analyses](https://causal-inference-r-workshop.netlify.app/11-tipr.html)
* [12 Whole Game (Your Turn)](https://causal-inference-r-workshop.netlify.app/12-whole_game-2.html)

### Installing materials locally

We will be using RStudio Cloud for the workshop, but if you would like to install the required packages and course materials, we have an R package called {[causalworkshop](https://github.com/malcolmbarrett/causalworkshop)} to help you do that! You can install {[causalworkshop](https://github.com/malcolmbarrett/causalworkshop)} from GitHub with:

``` r
install.packages("remotes")
remotes::install_github("malcolmbarrett/causalworkshop")
```

Once you've installed the package, install the workshop with

``` r
causalworkshop::install_workshop()
```

By default, this package downloads the materials to a conspicuous place like your Desktop. You can also tell `install_workshop()` exactly where to put the materials:

``` r
causalworkshop::install_workshop("a/path/on/your/computer")
```
