---
title: "Whole Game 2: Malaria and Mosquito Nets"
author: "Malcolm Barrett"
institute: "RStudio, PBC"
date: "2021-09-01 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    css: ["default", "theme.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      navigation:
        scroll: false 
      
---

class: inverse

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE, tibble.max_extra_cols = 6, tibble.width = 60)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.align = "center", dpi = 320, fig.height = 4)
library(tidyverse)
library(ggdag)
```

1. Specify causal question
2. Draw assumptions (causal diagram)
3. Model assumptions (e.g. with a propensity score)
4. Analyze propensities (diagnostics)
5. Estimate causal effects 
6. Conduct a sensitivity analysis

---

class: middle, center, inverse

# **Does mosquito bed net use reduce malaria risk?**

---

# The Data

```{r}
library(causalworkshop)
net_data
```

---

# Proposed DAG

```{r, echo = FALSE}
mosquito_dag <- dagify(
  malaria_risk ~ net + income + health + temperature + resistance,
  net ~ income + health + temperature + eligible + household,
  eligible ~ income + household,
  health ~ income,
  exposure = "net",
  outcome = "malaria_risk",
  coords = list(x = c(malaria_risk = 7, net = 3, income = 4, health = 5,
                      temperature = 6, resistance = 8.5, eligible = 2, household = 1),
                y = c(malaria_risk = 2, net = 2, income = 3, health = 1,
                      temperature = 3, resistance = 2, eligible = 3, household = 2)),
  labels = c(malaria_risk = "Risk of malaria", net = "Mosquito net", income = "Income",
             health = "Health", temperature = "Nighttime temperatures",
             resistance = "Insecticide resistance",
             eligible = "Eligible for program", household = "Number in household")
)

ggdag_status(mosquito_dag, use_labels = "label", text = FALSE) +
  guides(color = "none") +
  theme_dag() +
  labs(caption = "Thanks to Andrew Heiss for the data!") +
  coord_cartesian(clip = "off")
```

---

class: inverse, middle, center

# **Your Turn!**
